---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3c810c56c70061fc90cf94bd6730b476cd38d1ff
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/07/2019
ms.locfileid: "72015137"
---
# <a name="c28163"></a>C28163
警告 C28163：绝不应从 try/except 块中调用函数

 当函数的类型不应包含在 @no__t 1 块中，而该类型不应包含在 `try/except` 块中时，将报告此警告。 代码分析工具至少发现了一个路径，其中，所调用的函数都位于 `try/except` 块中。