---
title: C6242
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6242
helpviewer_keywords:
- C6242
ms.assetid: 523d46ce-8370-434c-a752-2e3a18cca9a5
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 825a294647f970d0e74be4d8dfab74dc82db3020
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/07/2019
ms.locfileid: "72013513"
---
# <a name="c6242"></a>C6242
警告 C6242：从此 try 块中跳转将强制本地展开。 导致严重的性能损失

 此警告表明，跳转语句会使控制流离开 try finally 的受保护块，而不是通过贯穿。

 除了从最后一条语句中的遍历以外，从最后一个语句到的受保护块仍需要进行本地展开。 本地展开通常需要大约1000个计算机指令;因此，这会对性能产生不利后果。

 使用 `_leave` 退出受保护的 try 块。

## <a name="example"></a>示例
 下面的代码将生成此警告：

```
#include <malloc.h>
void DoSomething(char *p); // function can throw exception

int f( )
{
   char *ptr = 0;
   __try
   {
      ptr = (char*) malloc(10);
      if ( !ptr )
      {
         return 0;   //Warning: 6242
      }
      DoSomething( ptr );
   }
   __finally
   {
      free( ptr );
   }
   return 1;
}
```

 若要更正此警告，请使用 `__leave`，如以下代码所示：

```
#include <malloc.h>
void DoSomething(char *p);
int f()
{
   char *ptr = 0;
   int retVal = 0;

   __try
   {
      ptr = (char *) malloc(10);
      if ( !ptr )
      {
         retVal = 0;
         __leave;   //No warning
      }
      DoSomething( ptr );
      retVal = 1;
   }
   __finally
   {
      free( ptr );
   }

   return retVal;
}
```

 在内存泄漏和异常方面，使用 malloc 和 free 具有许多缺陷。 若要避免这种类型的泄漏和异常问题，请使用C++标准模板库（STL）提供的机制。 其中包括[shared_ptr](/cpp/standard-library/shared-ptr-class)、 [unique_ptr](/cpp/standard-library/unique-ptr-class)和[矢量](/cpp/standard-library/vector)。 有关详细信息，请参阅[智能指针](/cpp/cpp/smart-pointers-modern-cpp)和[ C++标准库](/cpp/standard-library/cpp-standard-library-reference)。

## <a name="see-also"></a>请参阅
 [try-finally 语句](/cpp/cpp/try-finally-statement)