---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 47bb0843ab6048bbfa1b4ba881d3748a23de6dd9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449657"
---
# <a name="c6318"></a>C6318
警告 C6318： __try/\__except 错误：在异常筛选器表达式中使用常量 EXCEPTION_CONTINUE_SEARCH 或另一个计算结果为0的常量。 异常处理程序块中的代码不会执行

 此警告表明，如果此结构化异常处理程序的受保护块中发生异常，则将不会处理异常，因为在异常筛选器表达式中使用了常量 `EXCECPTION_CONTINUE_SEARCH`。

 此代码等效于不带异常处理程序块的受保护块，因为不执行处理程序块。

## <a name="example"></a>示例
 下面的代码将生成此警告：

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 若要更正此警告，请使用以下代码：

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>请参阅
 [try-except 语句](/cpp/cpp/try-except-statement)
