---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: be42518fd34867ff149849b70a470506c4e9cba9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449714"
---
# <a name="c6312"></a>C6312
警告 C6312：可能的无限循环：在 try 的异常筛选器表达式中使用常量 EXCEPTION_CONTINUE_EXECUTION

 此警告意味着使用结构化异常处理程序的筛选器表达式中的常量 `EXCEPTION_CONTINUE_EXECUTION` （或另一个计算结果为-1 的常量）。 使用常量值 `EXCEPTION_CONTINUE_EXECUTION` 可能会导致无限循环。 例如，如果硬件引发了异常，则会重新启动导致此异常的指令。 如果导致此异常的地址仍错误，则会出现另一个异常，并以相同的方式进行处理。 这将导致无限循环。

 对 `RaiseException` 的显式调用不会直接导致无限循环，但会继续执行受保护的块中的代码。 这可能是意外情况，如果使用 `RaiseException` 避免取消引用无效的指针，则可能会导致无限循环。

 通常，`EXCEPTION_CONTINUE_EXECUTION` 应仅由在筛选器表达式中调用的函数返回，该函数有机会修复导致异常的指针或基础内存。

## <a name="example"></a>示例
 下面的代码将生成此警告：

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 若要更正此警告，请使用以下代码：

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
