---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3bcce7f19fa5b8515a47f4bbe27c0e05ddbae9e8
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 02/15/2020
ms.locfileid: "77266974"
---
# <a name="c6320"></a>C6320
警告 C6320：异常筛选器表达式是常量 EXCEPTION_EXECUTE_HANDLER。 这可能会屏蔽不打算处理的异常

 此警告表明在 __except 块中使用 EXCEPTION_EXECUTE_HANDLER 常量的副作用。 在这种情况下，\__except 块中的语句始终会执行以处理异常，包括你不希望在特定函数中处理的异常。 建议在处理异常前检查异常。

## <a name="example"></a>示例
 下面的代码将生成此警告，因为 __except 块将尝试处理所有类型的异常：

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 若要更正此警告，请使用 `GetExceptionCode` 在处理特定异常之前检查该异常，如下面的代码所示：

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>另请参阅
 [try-except 语句](/cpp/cpp/try-except-statement)
