---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: c179a18c49ede3cfc654cd84bc11f93f7d3a6419
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/07/2019
ms.locfileid: "72012948"
---
# <a name="c6320"></a>C6320
警告 C6320：异常筛选器表达式是常量 EXCEPTION_EXECUTE_HANDLER。 这可能会屏蔽不打算处理的异常

 此警告表示在 __except 块中使用 EXCEPTION_EXECUTE_HANDLER 常量的副作用。 在这种情况下，将始终执行 @no__t 旁 1/-0 _except 块中的语句来处理异常，包括你不希望在特定函数中处理的异常。 建议在处理异常前检查异常。

## <a name="example"></a>示例
 下面的代码将生成此警告，因为 __except 块将尝试处理所有类型的异常：

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 若要更正此警告，请使用 `GetExceptionCode` 来检查是否有特定异常，然后再处理它，如下面的代码所示：

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>请参阅
 [try-except 语句](/cpp/cpp/try-except-statement)