---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: fef29c7f6e341cf4cd31991b24bfc209bd902b15
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781466"
---
# <a name="c6320"></a>C6320
警告 C6320： 异常筛选器表达式为常数 EXCEPTION_EXECUTE_HANDLER。 这可能会屏蔽不打算处理的异常

 此警告意味着使用 EXCEPTION_EXECUTE_HANDLER 常量在 __except 块的副作用。 在此情况下中的语句\_的 _except 块将始终执行来处理异常，包括您不希望在特定的函数中处理的异常。 建议您检查之前处理该异常。

## <a name="example"></a>示例
 下面的代码生成此警告，因为 __except 块就用来处理所有类型的异常：

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 若要更正此警告，请使用`GetExceptionCode`检查特定异常之前处理它，如下面的代码中所示：

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>请参阅
 [try-except 语句](/cpp/cpp/try-except-statement)